expr: Train ODE-Net (MNIST)

device: &device cuda:1
parallel: false

data:
  dataset: MNIST
  root: data/
  download: True
  mode: train

model:
  name: ODENet

hyperparameters:
  batch_size: 128
  optim: SGD
  lr: 0.1
  loss_fn: cross-entropy
  epochs: 160

save:
  name: odenet_mnist
  weights_path: saved/weights
  loss_path: saved/loss