expr: Train ResNet (MNIST)

device: &device cuda:0
parallel: false

data:
  dataset: MNIST
  root: data/
  download: True
  mode: train

model:
  name: ResNet

hyperparameters:
  batch_size: 128
  optim: SGD
  lr: 0.1
  loss_fn: cross-entropy
  epochs: 160

save:
  name: resnet_mnist
  weights_path: saved/weights
  loss_path: saved/loss