expr: Train RK-Net (MNIST)

device: &device cuda:0
parallel: false

data:
  dataset: MNIST
  root: data/
  download: true
  mode: train

model:
  name: OfficialODENet
  adjoint: false
  solver: dopri5

hyperparameters:
  batch_size: 128
  optim: SGD
  lr: 0.1
  loss_fn: cross-entropy
  epochs: 160

save:
  name: rknet_mnist
  weights_path: saved/weights
  loss_path: saved/loss